"use client";

import { useEffect, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { ReportError } from "@/components/ReportError";
import { getDiagramById } from "@/lib/registry";

const DIAGRAM_ID = "endo/thyroid-hormone-synthesis";
const diagram = getDiagramById(DIAGRAM_ID);

type StepId = 1 | 2 | 3 | 4 | 5 | 6 | 7;

type Step = {
  id: StepId;
  shortName: string;
  title: string;
  body: string;
  clinical: string;
};

const STEPS: Step[] = [
  {
    id: 1,
    shortName: "Iodide trap",
    title: "1. Iodide trapping (Na⁺/I⁻ symporter, NIS)",
    body: "The follicular cell concentrates I⁻ from blood (10–25 μM) into the cytoplasm (~250 μM) — a 30-fold gradient — using the Na⁺/I⁻ symporter on the BASOLATERAL membrane. Driven by Na⁺-K⁺ ATPase. TSH up-regulates NIS expression. Perchlorate, thiocyanate, and pertechnetate (Tc-99m) all compete with iodide here.",
    clinical: "Radioiodine therapy exploits this step — ¹³¹I⁻ uses the SAME NIS to concentrate inside thyroid cells and destroy them (Graves', toxic nodules, post-thyroidectomy remnant ablation). Failure to take up I⁻ defines 'cold' nodules — higher cancer risk."
  },
  {
    id: 2,
    shortName: "Pendrin → colloid",
    title: "2. Iodide moves to colloid via Pendrin",
    body: "Pendrin (an anion exchanger) on the APICAL membrane transports I⁻ from the cell into the colloid lumen. Less rate-limiting than NIS but essential.",
    clinical: "Pendred syndrome (autosomal recessive SLC26A4 mutation): congenital sensorineural deafness + euthyroid or mildly hypothyroid goiter. Pendrin also expressed in the inner ear and kidney."
  },
  {
    id: 3,
    shortName: "Thyroglobulin",
    title: "3. Thyroglobulin synthesised and secreted into colloid",
    body: "Thyroglobulin (Tg) is a 660-kDa glycoprotein with ~134 tyrosine residues, of which 25–30 are accessible for iodination. Synthesised in the rER → Golgi → exocytosis into the colloid. The colloid IS thyroglobulin storage — months of hormone supply.",
    clinical: "Serum Tg is a TUMOR MARKER after total thyroidectomy for differentiated thyroid cancer — should be undetectable. Detectable Tg → recurrence. Anti-Tg antibodies can interfere (assay artefact)."
  },
  {
    id: 4,
    shortName: "Oxidation (TPO)",
    title: "4. Iodide oxidation by thyroid peroxidase (TPO)",
    body: "TPO at the apical membrane oxidises 2 I⁻ → I₂ (or iodinium I⁺), using H₂O₂ as electron acceptor (generated by DUOX2). This is the rate-limiting step of iodination chemistry.",
    clinical: "Thionamides (propylthiouracil PTU, methimazole) INHIBIT TPO → block both oxidation and organification. PTU also blocks peripheral T4 → T3 conversion (5'-deiodinase) — preferred in thyroid storm. Methimazole is otherwise first-line; PTU has rare but lethal hepatotoxicity."
  },
  {
    id: 5,
    shortName: "Organification",
    title: "5. Organification — iodination of tyrosyl residues",
    body: "TPO also iodinates tyrosine residues on thyroglobulin, generating monoiodotyrosine (MIT) and diiodotyrosine (DIT). Still attached to the Tg backbone in the colloid.",
    clinical: "The same TPO enzyme is responsible for BOTH oxidation and organification — that's why thionamides hit both. Anti-TPO antibodies are the serologic signature of Hashimoto's thyroiditis (and present in many patients with Graves' too)."
  },
  {
    id: 6,
    shortName: "Coupling",
    title: "6. Coupling of iodotyrosines",
    body: "TPO catalyses coupling reactions on adjacent iodotyrosines (still on Tg): MIT + DIT → T3, and DIT + DIT → T4. T4 is the predominant product (~80% of follicular output by mass); T3 (~20% from the follicle, ~80% from peripheral 5'-deiodination of T4) is the metabolically active hormone.",
    clinical: "Wolff–Chaikoff effect: an acute iodide load TRANSIENTLY blocks organification and coupling — protective autoregulation. Escape after ~24–48 h. Lugol's iodine used pre-thyroidectomy exploits this to shrink the gland."
  },
  {
    id: 7,
    shortName: "Endocytosis + release",
    title: "7. Endocytosis of Tg, lysosomal cleavage, hormone release",
    body: "TSH stimulates the apical membrane to endocytose colloid droplets containing iodinated Tg. Lysosomal proteases cleave Tg → T4, T3, MIT, and DIT. T4 and T3 cross the basolateral membrane into the blood; MIT and DIT have their iodide salvaged by intrathyroidal deiodinase. ~90% of secreted hormone is T4.",
    clinical: "Levothyroxine (synthetic T4) replicates this output — taken on an empty stomach, half-life ~7 days. Liothyronine (T3) is fast-on, fast-off (half-life 1 day) — used short-term or in severe hypothyroid edema where peripheral conversion is impaired."
  }
];

export default function ThyroidHormoneSynthesisWidget() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const initial = Number(searchParams.get("step") ?? 1) as StepId;
  const [stepId, setStepId] = useState<StepId>(STEPS.some((s) => s.id === initial) ? initial : 1);
  const urlTimer = useRef<number | undefined>(undefined);

  useEffect(() => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("step", String(stepId));
    const next = params.toString();
    if (next === searchParams.toString()) return;
    window.clearTimeout(urlTimer.current);
    urlTimer.current = window.setTimeout(() => {
      router.replace(`${pathname}?${next}`, { scroll: false });
    }, 180);
    return () => window.clearTimeout(urlTimer.current);
  }, [stepId, pathname, router, searchParams]);

  useEffect(() => {
    const next = Number(searchParams.get("step") ?? 1) as StepId;
    if (STEPS.some((s) => s.id === next)) setStepId(next);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams]);

  const step = STEPS.find((s) => s.id === stepId)!;
  const W = 760;
  const H = 460;
  const highlight = (id: StepId) => (stepId === id ? "var(--ph-curve-1)" : "var(--ph-axis)");
  const highlightWidth = (id: StepId) => (stepId === id ? 3 : 1.5);

  return (
    <section className="ph-widget-shell">
      <section className="ph-concept-panel p-4">
        <p className="ph-section-label">Concept scan</p>
        <p className="mt-2 max-w-5xl text-sm font-medium text-ph-muted">{diagram.concept}</p>
      </section>

      <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-start">
        <section className="ph-panel ph-chart-stage p-4" aria-label="Thyroid follicle schematic">
          <div aria-live="polite" className="mb-3 ph-clay-well p-3">
            <p className="ph-section-label">{step.title}</p>
            <p className="mt-1.5 text-sm text-ph-muted">{step.body}</p>
            <p className="mt-2 text-sm">
              <span className="font-bold text-ph-text">Clinical:</span>{" "}
              <span className="text-ph-muted">{step.clinical}</span>
            </p>
          </div>

          <svg role="img" aria-label={step.title} viewBox={`0 0 ${W} ${H}`} className="ph-pathway-canvas h-auto w-full">
            {/* Blood capillary (top band) */}
            <g>
              <rect x={40} y={30} width={680} height={50} rx={8} fill="color-mix(in srgb, var(--ph-curve-4), transparent 88%)" stroke="color-mix(in srgb, var(--ph-curve-4), transparent 55%)" strokeWidth={1.5} />
              <text x={56} y={56} fontSize="11" fontWeight="700" fill="var(--ph-muted)" letterSpacing="1.5">
                BLOOD CAPILLARY (basolateral side)
              </text>
              {/* I- in blood */}
              {Array.from({ length: 8 }).map((_, i) => (
                <g key={i}>
                  <circle cx={140 + i * 60} cy={60} r={5} fill="var(--ph-curve-4)" />
                  <text x={140 + i * 60} y={64} textAnchor="middle" fontSize="8" fontWeight="800" fill="white">I⁻</text>
                </g>
              ))}
              {/* T4/T3 release into blood (step 7) */}
              {stepId === 7 ? (
                <g>
                  <text x={580} y={56} fontSize="14" fontWeight="800" fill="var(--ph-curve-6)">↑</text>
                  <text x={620} y={58} fontSize="11" fontWeight="800" fill="var(--ph-curve-6)">T4 / T3 → blood</text>
                </g>
              ) : null}
            </g>

            {/* Follicular cell (middle band) */}
            <g>
              <rect x={40} y={100} width={680} height={150} rx={10} fill="color-mix(in srgb, var(--ph-surface), black 3%)" stroke="var(--ph-axis)" strokeWidth={1.5} />
              <text x={56} y={120} fontSize="11" fontWeight="700" fill="var(--ph-muted)" letterSpacing="1.5">
                FOLLICULAR CELL
              </text>

              {/* NIS on basolateral */}
              <g>
                <rect x={120} y={88} width={50} height={28} rx={4} fill={stepId === 1 ? "var(--ph-curve-2)" : "color-mix(in srgb, var(--ph-curve-2), transparent 80%)"} stroke={highlight(1)} strokeWidth={highlightWidth(1)} />
                <text x={145} y={106} textAnchor="middle" fontSize="10" fontWeight="800" fill="white">NIS</text>
                <text x={145} y={138} textAnchor="middle" fontSize="9" fontWeight="700" fill="var(--ph-muted)">Na⁺/I⁻</text>
                {stepId === 1 ? <text x={145} y={158} textAnchor="middle" fontSize="14" fontWeight="800" fill="var(--ph-curve-2)">↓ I⁻</text> : null}
              </g>

              {/* Pendrin on apical */}
              <g>
                <rect x={220} y={232} width={50} height={28} rx={4} fill={stepId === 2 ? "var(--ph-curve-3)" : "color-mix(in srgb, var(--ph-curve-3), transparent 80%)"} stroke={highlight(2)} strokeWidth={highlightWidth(2)} />
                <text x={245} y={250} textAnchor="middle" fontSize="9" fontWeight="800" fill="white">Pendrin</text>
                {stepId === 2 ? <text x={245} y={222} textAnchor="middle" fontSize="14" fontWeight="800" fill="var(--ph-curve-3)">↑ I⁻</text> : null}
              </g>

              {/* I- in cytoplasm */}
              {stepId >= 1 ? Array.from({ length: 6 }).map((_, i) => (
                <g key={`cyto-${i}`}>
                  <circle cx={180 + i * 35} cy={170} r={5} fill="var(--ph-curve-2)" />
                  <text x={180 + i * 35} y={174} textAnchor="middle" fontSize="8" fontWeight="800" fill="white">I⁻</text>
                </g>
              )) : null}

              {/* Tg synthesis (ER + Golgi) */}
              <g>
                <rect x={420} y={150} width={120} height={48} rx={6} fill={stepId === 3 ? "color-mix(in srgb, var(--ph-curve-1), transparent 80%)" : "color-mix(in srgb, var(--ph-surface), black 6%)"} stroke={highlight(3)} strokeWidth={highlightWidth(3)} />
                <text x={480} y={175} textAnchor="middle" fontSize="10" fontWeight="800" fill="var(--ph-text)">rER → Golgi</text>
                <text x={480} y={190} textAnchor="middle" fontSize="9" fontWeight="700" fill="var(--ph-muted)">Tg synthesis</text>
              </g>
            </g>

            {/* Apical membrane border */}
            <line x1={40} y1={260} x2={720} y2={260} stroke="var(--ph-axis)" strokeWidth={1.5} />
            <text x={720} y={252} textAnchor="end" fontSize="9" fontWeight="700" fill="var(--ph-muted)" letterSpacing="1">
              APICAL MEMBRANE
            </text>

            {/* Colloid (bottom band) */}
            <g>
              <rect x={40} y={270} width={680} height={160} rx={10} fill="color-mix(in srgb, var(--ph-curve-2), transparent 92%)" stroke="color-mix(in srgb, var(--ph-curve-2), transparent 60%)" strokeWidth={1.5} />
              <text x={56} y={290} fontSize="11" fontWeight="700" fill="var(--ph-muted)" letterSpacing="1.5">
                COLLOID LUMEN
              </text>

              {/* TPO on apical membrane (steps 4-5) */}
              <g>
                <rect x={350} y={244} width={50} height={28} rx={4} fill={stepId === 4 || stepId === 5 ? "var(--ph-curve-4)" : "color-mix(in srgb, var(--ph-curve-4), transparent 80%)"} stroke={stepId === 4 || stepId === 5 ? "var(--ph-curve-4)" : "var(--ph-axis)"} strokeWidth={stepId === 4 || stepId === 5 ? 3 : 1.2} />
                <text x={375} y={262} textAnchor="middle" fontSize="10" fontWeight="800" fill="white">TPO</text>
                {stepId === 4 ? <text x={375} y={232} textAnchor="middle" fontSize="11" fontWeight="800" fill="var(--ph-curve-4)">+ H₂O₂</text> : null}
              </g>

              {/* Tg in colloid with MIT/DIT/T3/T4 */}
              <g>
                <rect x={120} y={310} width={520} height={70} rx={10} fill="color-mix(in srgb, var(--ph-surface), black 4%)" stroke={stepId === 5 || stepId === 6 ? "var(--ph-curve-1)" : "var(--ph-axis)"} strokeWidth={stepId === 5 || stepId === 6 ? 2 : 1} />
                <text x={140} y={330} fontSize="10" fontWeight="800" fill="var(--ph-text)">Tg backbone</text>
                {stepId >= 5
                  ? ["MIT", "DIT", "MIT", "DIT", "DIT", "DIT", "T3", "T4"].slice(0, stepId === 5 ? 6 : 8).map((label, i) => (
                      <g key={i}>
                        <rect x={180 + i * 56} y={342} width={44} height={26} rx={4} fill={label.startsWith("T") ? "var(--ph-curve-6)" : "var(--ph-curve-2)"} />
                        <text x={202 + i * 56} y={360} textAnchor="middle" fontSize="11" fontWeight="800" fill="white">{label}</text>
                      </g>
                    ))
                  : null}
              </g>

              {/* Endocytosis (step 7) */}
              {stepId === 7 ? (
                <g>
                  <ellipse cx={420} cy={398} rx={50} ry={20} fill="none" stroke="var(--ph-curve-3)" strokeWidth={2.5} strokeDasharray="6 4" />
                  <text x={420} y={420} textAnchor="middle" fontSize="11" fontWeight="800" fill="var(--ph-curve-3)">
                    endocytosis · lysosome cleaves Tg
                  </text>
                </g>
              ) : null}
            </g>
          </svg>
        </section>

        <aside className="grid gap-4">
          <section className="ph-panel p-4" aria-label="Step selector">
            <h2 className="ph-section-label mb-4">Walk the follicle</h2>
            <div className="grid gap-2">
              {STEPS.map((s) => {
                const isSelected = s.id === stepId;
                return (
                  <button
                    key={s.id}
                    type="button"
                    onClick={() => setStepId(s.id)}
                    className={`focus-ring rounded-ph border px-3 py-2 text-left text-sm transition ${
                      isSelected
                        ? "border-[color-mix(in_srgb,var(--ph-accent),transparent_45%)] bg-[color-mix(in_srgb,var(--ph-accent),transparent_85%)] text-ph-accent"
                        : "ph-clay-button text-ph-muted"
                    }`}
                  >
                    <span className="font-bold tabular-nums">{s.id}.</span> <span className="font-bold">{s.shortName}</span>
                  </button>
                );
              })}
            </div>
            <div className="mt-4 flex justify-between gap-2">
              <button
                type="button"
                onClick={() => stepId > 1 && setStepId((stepId - 1) as StepId)}
                disabled={stepId === 1}
                className="focus-ring ph-clay-button px-3 py-2 text-xs font-semibold uppercase tracking-[0.1em] text-ph-muted disabled:opacity-40 hover:border-[var(--ph-border-strong)] hover:text-ph-text"
              >
                ← Prev
              </button>
              <button
                type="button"
                onClick={() => stepId < 7 && setStepId((stepId + 1) as StepId)}
                disabled={stepId === 7}
                className="focus-ring ph-clay-button px-3 py-2 text-xs font-semibold uppercase tracking-[0.1em] text-ph-muted disabled:opacity-40 hover:border-[var(--ph-border-strong)] hover:text-ph-text"
              >
                Next →
              </button>
            </div>
          </section>

          <section className="ph-panel p-4" aria-label="References">
            <h2 className="ph-section-label mb-3">References</h2>
            <ul className="grid gap-2 text-sm text-ph-muted">
              {diagram.references.map((reference) => (
                <li key={`${reference.source}-${reference.pages}`}>
                  {reference.source}
                  {reference.pages ? `, ${reference.pages}` : ""}
                </li>
              ))}
            </ul>
          </section>
        </aside>
      </div>

      <ReportError diagramId={DIAGRAM_ID} />
    </section>
  );
}
